### ISSUE TITLE
use standard xdg cache locations instead of polluting home

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [nhoffman/mkvenv#1]
its good practice to use ~/.cache/<something>

**Comment by nhoffman** [comment]
Thanks for the comment. I'd like to learn more about this - in my experience (admittedly limited to OS X and ubuntu) the vast majority of applications store data in $HOME as hidden directories. Is the XDG standard frequently respected outside of freedesktop.org projects?

**Comment by RonnyPfannschmidt** [comment]
bascially all "nice" programs follow it

**Comment by nhoffman** [comment]
Seems like a good approach would be to follow conventions used by pip itself - in 'pip/locations.py', looks like assets are stored under `site.USER_SITE`. I really don't want to have to reimplement the xdg standard in a system-independent way, and don't want to introduce a dependency like PyXDG. Suggestions and pull requests are welcome. Marked as an enhancement. For now, wheels are saved to '~/.mkvenv'

**Comment by RonnyPfannschmidt** [comment]
closing to get if off my plate on github
